# Tenderly Web3 Actions Configuration
# Project: Ua_0357/testnet
# Project ID: 9a44e073-c1cc-41bf-8737-c4070d277bf2
# Dashboard: https://dashboard.tenderly.co/Ua_0357/project/testnet/9a44e073-c1cc-41bf-8737-c4070d277bf2/rpc-builder

project_slug: Ua_0357/testnet
access_key: LZAQjWhTiJJUskQJQXUzAw2ZE0EJpNni
